### ISSUE TITLE
Request to be Added Tor Instant Messenger

### ISSUE THREAD

**Issue by PowerPress** [maqp/tfc-otp#1]
This is a wonderful project. Right now Tor is working building an IM solution utilizing InstantBirdand they are working on OTR based integration. Your software is a perfect fit and could be requested to be added while they work on OTR which could ensure that they make sure their code is compatible with TFC. 

Please consider contacting them @ https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger

**Comment by maqp** [comment]
Thank you for posting this. [Link to ticket](https://trac.torproject.org/projects/tor/ticket/17580).
